FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends 

WORKDIR /app

COPY requirements/parser.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download pl_core_news_lg

COPY parser/ /app/parser/
COPY backend/ /app/backend/
COPY config.py /app/config.py

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "parser.wiki"]